const journeyAsset = "./assets/live/diagnosis-journey/";

export const diagnosisJourney = [
  {
    id: "ai-readiness",
    shortLabel: "AI 진단",
    title: "AI 기반 창업 준비도 진단",
    subtitle: "창업 단계, MVP, 시장검증, 자금, 사업계획서를 입력해 AI 진단의 근거를 구성합니다.",
    tone: {
      accent: "#5b6bff",
      soft: "#eef1ff",
      wash: "#f7f8ff",
    },
    steps: [
      {
        id: "storage",
        label: "저장 방식",
        title: "입력 데이터의 저장 방식을 선택",
        image: `${journeyAsset}01-storage-mode.png`,
        alt: "입력 데이터 저장 방식 선택 화면",
        route: "/founder/diagnosis/storage",
        role: "진단 이력을 일회성으로 볼지, 이후 추천과 성장 추적에 계속 활용할지 결정합니다.",
        input: "저장 방식, 개인정보 처리 안내 확인",
        output: "진단 데이터 관리 기준 확정",
        next: "기관 공유 범위 선택",
      },
      {
        id: "sharing",
        label: "공유 범위",
        title: "기관 연결을 위한 데이터 공유 범위 선택",
        image: `${journeyAsset}02-sharing-scope.png`,
        alt: "기관 공유 범위 선택 화면",
        route: "/founder/diagnosis/sharing",
        role: "지원기관이 볼 수 있는 정보를 요약만 공유할지, 선택 항목까지 공유할지 분리합니다.",
        input: "공유 범위, 기관 연결 동의",
        output: "기관 추천과 상담 연결에 쓸 데이터 범위",
        next: "창업 단계 입력",
      },
      {
        id: "stage",
        label: "창업 단계",
        title: "현재 창업 단계 선택",
        image: `${journeyAsset}03-startup-stage.png`,
        alt: "현재 창업 단계 선택 화면",
        route: "/founder/intake/stage",
        role: "아이디어, 시장조사, MVP, 초기 고객 등 현재 위치를 기준으로 진단 기준을 맞춥니다.",
        input: "창업 단계",
        output: "동일 단계 창업자와 비교할 기준",
        next: "업종과 활동 지역 입력",
      },
      {
        id: "industry-region",
        label: "업종·지역",
        title: "아이템 업종과 활동 지역 입력",
        image: `${journeyAsset}04-industry-region.png`,
        alt: "아이템 업종과 활동 지역 입력 화면",
        route: "/founder/intake/industry-region",
        role: "지역 창업지원센터, 멘토링, 지원사업 후보를 찾기 위한 기본 맥락을 만듭니다.",
        input: "업종, 아이템 설명, 활동 지역",
        output: "지역·업종 기반 추천 조건",
        next: "MVP 링크 확인",
      },
      {
        id: "mvp-link",
        label: "MVP",
        title: "공유 가능한 MVP 링크 확인",
        image: `${journeyAsset}05-mvp-link.png`,
        alt: "공유 가능한 MVP 링크 입력 화면",
        route: "/founder/intake/mvp",
        role: "실행준비도와 시장검증 근거를 판단할 수 있는 MVP 존재 여부를 확인합니다.",
        input: "MVP URL, MVP 상태",
        output: "MVP 검증 또는 MVP 보완 액션 기준",
        next: "시장검증과 자금 입력",
      },
      {
        id: "market-funding-intro",
        label: "시장검증·자금",
        title: "시장검증과 자금 입력 시작",
        image: `${journeyAsset}06-market-funding-intro.png`,
        alt: "시장검증과 자금 입력 안내 화면",
        route: "/founder/intake/market-funding",
        role: "시장검증과 자금 입력은 AI 기반 창업 준비도 진단의 핵심 입력 구간입니다.",
        input: "고객 인터뷰, 테스트 사용자, 유료 고객 여부, 자금 상태",
        output: "시장검증도·안정성·정책금융 준비도 판단 근거",
        next: "고객 검증 현황 입력",
      },
      {
        id: "customer-validation",
        label: "고객 검증",
        title: "고객 인터뷰와 테스트 사용자 수 입력",
        image: `${journeyAsset}07-customer-validation.png`,
        alt: "고객 인터뷰와 테스트 사용자 수 입력 화면",
        route: "/founder/intake/customer-validation",
        role: "AI가 추정이 아니라 실제 고객 접점 근거를 바탕으로 시장검증도를 판단하도록 합니다.",
        input: "고객 인터뷰 수, 테스트 사용자 수",
        output: "고객 검증량 기준",
        next: "고객 반응 유형 선택",
      },
      {
        id: "purchase-intent",
        label: "구매 의사",
        title: "고객 반응 유형 선택",
        image: `${journeyAsset}08-purchase-intent.png`,
        alt: "고객 반응 유형 선택 화면",
        route: "/founder/intake/purchase-intent",
        role: "메모·설문·인터뷰 녹취처럼 반응의 신뢰도를 구분합니다.",
        input: "고객 반응 유형",
        output: "시장검증 근거의 질",
        next: "자금 런웨이 계산",
      },
      {
        id: "runway",
        label: "런웨이",
        title: "현재 자금으로 버틸 수 있는 기간 입력",
        image: `${journeyAsset}09-runway.png`,
        alt: "자금 런웨이 입력 화면",
        route: "/founder/intake/runway",
        role: "운영 안정성과 지원사업 신청 우선순위를 판단할 자금 지속 가능성을 계산합니다.",
        input: "보유 자금, 월 고정비",
        output: "예상 런웨이와 안정성 근거",
        next: "매출 계획 입력",
      },
      {
        id: "revenue-plan",
        label: "매출 계획",
        title: "앞으로의 매출 계획 입력",
        image: `${journeyAsset}10-revenue-plan.png`,
        alt: "앞으로의 매출 계획 입력 화면",
        route: "/founder/intake/revenue",
        role: "계획 매출과 실제 성장 추적을 비교할 기준값을 만듭니다.",
        input: "3개월·6개월·12개월 예상 매출",
        output: "성장성과 안정성 평가 기준",
        next: "사업계획서 구조화 시작",
      },
      {
        id: "business-plan-intro",
        label: "사업계획",
        title: "아이디어와 사업계획서 구조화 시작",
        image: `${journeyAsset}11-business-plan-intro.png`,
        alt: "아이디어와 사업계획서 구조화 안내 화면",
        route: "/founder/intake/business-plan",
        role: "문제정의, 솔루션, 차별성, 시장 규모, 자금 사용계획을 같은 흐름으로 정리합니다.",
        input: "사업계획 입력 안내 확인",
        output: "사업계획서 진단 구간 진입",
        next: "문제 정의 입력",
      },
      {
        id: "problem-definition",
        label: "문제 정의",
        title: "해결하려는 문제 입력",
        image: `${journeyAsset}12-problem-definition.png`,
        alt: "문제 정의 입력 화면",
        route: "/founder/intake/problem-definition",
        role: "누구의 어떤 손실을 줄이는지 명확히 해 솔루션과 추천사업의 근거를 만듭니다.",
        input: "고객, 상황, 불편, 손실",
        output: "문제정의 근거",
        next: "솔루션 입력",
      },
      {
        id: "solution",
        label: "솔루션",
        title: "문제를 해결하는 방식 입력",
        image: `${journeyAsset}13-solution.png`,
        alt: "솔루션 입력 화면",
        route: "/founder/intake/solution",
        role: "기능 나열이 아니라 고객 문제가 어떻게 줄어드는지 평가합니다.",
        input: "핵심 기능, 제공 가치, 구현 상태",
        output: "솔루션 구체성 기준",
        next: "차별성과 시장 규모 입력",
      },
      {
        id: "differentiation-market",
        label: "차별성·시장",
        title: "차별성과 시장 규모 입력",
        image: `${journeyAsset}14-differentiation-market.png`,
        alt: "차별성과 시장 규모 입력 화면",
        route: "/founder/intake/differentiation",
        role: "성장성과 사업계획서 완성도를 판단할 경쟁·시장 근거를 정리합니다.",
        input: "기존 대안, 차별성, 시장 규모",
        output: "성장성·차별성 평가 근거",
        next: "자금 사용계획 입력",
      },
      {
        id: "fund-use-plan",
        label: "자금 사용",
        title: "자금 사용계획과 전체 계획 입력",
        image: `${journeyAsset}15-fund-use-plan.png`,
        alt: "자금 사용계획 입력 화면",
        route: "/founder/intake/fund-use-plan",
        role: "정책금융 준비도와 지원사업 제출 가능성을 판단하는 비용·목적 근거를 만듭니다.",
        input: "필요 자금, 항목별 사용계획, 사업계획서 요약",
        output: "정책금융 준비도 평가 근거",
        next: "입력정보 검토",
      },
      {
        id: "review",
        label: "검토",
        title: "입력정보 최종 검토",
        image: `${journeyAsset}16-review-submit.png`,
        alt: "입력정보 최종 검토 화면",
        route: "/founder/diagnosis/review",
        role: "AI 진단을 시작하기 전 입력 근거가 빠졌는지 마지막으로 확인합니다.",
        input: "전체 입력값 검토",
        output: "AI 진단 실행 준비 완료",
        next: "AI 진단 결과 확인",
      },
    ],
  },
  {
    id: "ai-result",
    shortLabel: "결과",
    title: "AI 진단 결과",
    subtitle: "입력 근거를 바탕으로 종합 결과, 5대 준비도, 최종 유형, 위험요인을 확인합니다.",
    tone: {
      accent: "#7657ff",
      soft: "#f1edff",
      wash: "#faf7ff",
    },
    steps: [
      {
        id: "result-summary",
        label: "요약",
        title: "창업 준비도 진단 결과 요약",
        image: `${journeyAsset}17-ai-result-summary.png`,
        alt: "AI 창업 준비도 진단 결과 요약 화면",
        route: "/founder/diagnosis/demo/summary",
        role: "성장 준비도, 정책금융 준비도, 기관 연결 가능 여부를 한 화면에서 요약합니다.",
        input: "AI가 분석한 전체 입력 근거",
        output: "핵심 점수와 한 줄 진단",
        next: "리포트 종합 보기",
      },
      {
        id: "result-report",
        label: "종합 리포트",
        title: "AI 진단 종합 리포트",
        image: `${journeyAsset}18-ai-result-report.png`,
        alt: "AI 진단 종합 리포트 화면",
        route: "/founder/diagnosis/demo/result",
        role: "결과를 끝으로 두지 않고 다음 실행 계획으로 이어지도록 리포트 구조를 보여줍니다.",
        input: "입력 데이터와 AI 평가 결과",
        output: "강점, 보완 필요, 추천 액션 요약",
        next: "상세 점수 보기",
      },
      {
        id: "scores",
        label: "5대 준비도",
        title: "5대 준비도 점수 확인",
        image: `${journeyAsset}19-readiness-scores.png`,
        alt: "5대 준비도 점수 화면",
        route: "/founder/diagnosis/demo/scores",
        role: "성장성, 안정성, 시장검증도, 실행준비도, 정책금융 준비도를 분리해 보여줍니다.",
        input: "진단 점수 산식 결과",
        output: "5개 준비도별 강점과 약점",
        next: "최종 유형 보기",
      },
      {
        id: "final-type",
        label: "최종 유형",
        title: "창업 유형 분류",
        image: `${journeyAsset}20-final-type.png`,
        alt: "창업 최종 유형 분류 화면",
        route: "/founder/diagnosis/demo/type",
        role: "현재 창업 상태를 행동 우선순위 중심의 유형으로 분류합니다.",
        input: "5대 준비도와 위험요인",
        output: "균형 준비형 등 최종 유형과 분류 근거",
        next: "위험요인 확인",
      },
      {
        id: "risk",
        label: "위험요인",
        title: "보완이 필요한 위험요인 확인",
        image: `${journeyAsset}21-risk-factors.png`,
        alt: "보완이 필요한 위험요인 화면",
        route: "/founder/diagnosis/demo/risk",
        role: "낮은 점수를 단순 경고로 끝내지 않고 실행 가능한 보완 항목으로 전환합니다.",
        input: "근거 부족 항목, 정책금융 준비도, 시장검증 상태",
        output: "보완해야 할 위험요인 목록",
        next: "Next Action 확인",
      },
    ],
  },
  {
    id: "next-action",
    shortLabel: "Next Action",
    title: "Next Action",
    subtitle: "가장 먼저 보완해야 할 항목을 실행 우선순위로 정리합니다.",
    tone: {
      accent: "#24a68a",
      soft: "#eaf8f3",
      wash: "#f6fcfa",
    },
    steps: [
      {
        id: "priority-actions",
        label: "우선순위",
        title: "우선 보완 액션 확인",
        image: `${journeyAsset}22-next-action.png`,
        alt: "우선 보완 액션 화면",
        route: "/founder/diagnosis/demo/actions",
        role: "최종 유형, 우선 보완 영역, 가장 낮은 점수, 다음 목표를 한 번에 연결합니다.",
        input: "AI 진단 결과와 위험요인",
        output: "고객 인터뷰, MVP 테스트, 자금계획, 사업계획서 보완 액션",
        next: "보완 액션 1부터 확인",
      },
    ],
  },
  {
    id: "repair-actions",
    shortLabel: "보완 액션",
    title: "보완 액션 1~4",
    subtitle: "진단 결과를 실제 제출·상담 준비물로 바꾸는 네 가지 보완 과제입니다.",
    tone: {
      accent: "#e98542",
      soft: "#fff2e7",
      wash: "#fffaf5",
    },
    steps: [
      {
        id: "action-interview",
        label: "1. 고객 인터뷰",
        title: "고객 인터뷰 근거 보완",
        image: `${journeyAsset}23-action-customer-interview.png`,
        alt: "고객 인터뷰 근거 보완 화면",
        route: "/founder/diagnosis/demo/interview",
        role: "고객 문제 반복성, 지불 의사, MVP 개선 근거를 인터뷰로 보완하게 합니다.",
        input: "현재 인터뷰 수, 유료 고객 인터뷰 여부",
        output: "추가 인터뷰 목표와 질문 예시",
        next: "MVP 테스트 액션",
      },
      {
        id: "action-mvp",
        label: "2. MVP 테스트",
        title: "MVP 테스트 결과 정리",
        image: `${journeyAsset}24-action-mvp-test.png`,
        alt: "MVP 테스트와 자금계획 보완 화면",
        route: "/founder/diagnosis/demo/mvptest",
        role: "테스트 사용자 피드백을 항목별로 정리해 시장검증 근거로 바꾸게 합니다.",
        input: "테스트 사용자 수, MVP 상태, 피드백",
        output: "피드백 정리와 다음 테스트 라운드 계획",
        next: "자금계획 수정",
      },
      {
        id: "action-funding",
        label: "3. 자금계획",
        title: "자금계획 수정",
        image: `${journeyAsset}25-action-funding-plan.png`,
        alt: "MVP 테스트와 자금계획 보완 화면",
        route: "/founder/diagnosis/demo/mvptest",
        role: "MVP 개발비, 마케팅비, 운영비를 항목별로 나눠 정책금융 준비도를 높입니다.",
        input: "보유 자금, 월 고정비, 예상 런웨이",
        output: "항목별 예산과 지원사업 신청용 자금계획",
        next: "사업계획서 개선",
      },
      {
        id: "action-business-plan",
        label: "4. 사업계획서",
        title: "사업계획서 근거 보완",
        image: `${journeyAsset}26-action-business-plan.png`,
        alt: "사업계획서 부족 근거 보완 화면",
        route: "/founder/diagnosis/demo/planfix",
        role: "문제정의, 솔루션, 차별성, 자금 사용계획의 근거 부족 여부를 항목별로 정리합니다.",
        input: "문제정의, 솔루션, 차별성, 자금 사용계획",
        output: "검토 가능·보완 필요·근거 부족 항목과 개선 문장 예시",
        next: "지원사업 추천 보기",
      },
    ],
  },
  {
    id: "support-programs",
    shortLabel: "지원사업",
    title: "지원사업",
    subtitle: "진단과 보완 과제를 바탕으로 추천 지원사업 후보와 완료 후 대시보드 흐름을 보여줍니다.",
    tone: {
      accent: "#3297d3",
      soft: "#eaf7ff",
      wash: "#f5fbff",
    },
    steps: [
      {
        id: "programs",
        label: "추천 후보",
        title: "추천 지원사업 후보 확인",
        image: `${journeyAsset}27-support-programs.png`,
        alt: "추천 지원사업 후보 화면",
        route: "/founder/diagnosis/demo/programs",
        role: "추천은 신청 가능 확정이 아니라 자격 조건과 보완 필요 항목을 함께 보는 후보 목록입니다.",
        input: "진단 결과, 보완 과제, 지역·업종 정보",
        output: "예비창업패키지, 초기창업패키지, 지역 창업지원센터 멘토링 후보",
        next: "진단 완료 후 대시보드",
      },
      {
        id: "dashboard-return",
        label: "대시보드",
        title: "진단 완료 후 대시보드 복귀",
        image: `${journeyAsset}28-dashboard-return.png`,
        alt: "진단 완료 후 대시보드 화면",
        route: "/founder/dashboard",
        role: "AI 진단 요약, 부족한 항목 TOP 3, 이번 주 보완 액션, 기관 매칭 상태를 운영 화면으로 연결합니다.",
        input: "진단 완료 결과",
        output: "추적 가능한 보완 액션과 기관 추천 현황",
        next: "성장 추적과 상담 관리",
      },
    ],
  },
];

export const founderTypes = [
  {
    name: "시장검증 보완형",
    signal: "고객 반응 근거가 부족한 상태",
    question: "고객이 실제로 원하고 비용을 낼 문제인가?",
    meaning: "문제정의와 아이디어는 있지만 인터뷰, 설문, 테스트 사용자, 유료 전환 같은 실제 고객 반응 데이터가 아직 약한 유형입니다.",
    action: "고객 인터뷰와 MVP 테스트를 먼저 보완해 시장검증도 근거를 채웁니다.",
    support: "고객발굴, 시장검증, PoC, 초기 실증 프로그램",
    tone: "blue",
  },
  {
    name: "실행역량 강화형",
    signal: "만들고 운영할 계획이 부족한 상태",
    question: "실제로 만들고 운영할 준비가 되어 있는가?",
    meaning: "시장성은 보이지만 팀 역할, MVP 범위, 일정, 운영 리스크 대응처럼 실행 계획의 구체성이 부족한 유형입니다.",
    action: "MVP 범위, 팀 역할, 실행 로드맵, 운영 리스크 대응안을 먼저 정리합니다.",
    support: "창업교육, 멘토링, MVP 제작, 초기 사업화 프로그램",
    tone: "violet",
  },
  {
    name: "자금계획·지원사업 준비형",
    signal: "신청 조건과 자금 사용계획이 부족한 상태",
    question: "지원사업 신청 요건과 자금계획이 맞는가?",
    meaning: "지원사업을 신청할 수는 있지만 자금 사용계획, 제출 서류, 공고 조건 적합성, 증빙 자료가 아직 정리되지 않은 유형입니다.",
    action: "항목별 예산, 사업비 사용 근거, 제출 서류, 지원사업 조건 체크를 우선 보완합니다.",
    support: "예비창업패키지, 사업화 자금, 지역 창업지원사업",
    tone: "amber",
  },
  {
    name: "균형 준비형",
    signal: "전반적 준비도는 균형적이나 우선순위가 필요한 상태",
    question: "어떤 순서로 고도화해야 하는가?",
    meaning: "5대 준비도가 비교적 고르게 분포하지만, 특정 근거를 더 보강하면 기관 상담과 지원사업 연결 가능성을 높일 수 있는 유형입니다.",
    action: "가장 낮은 준비도부터 고객검증, 자금계획, 사업계획서 근거를 순서대로 보완합니다.",
    support: "사업화 보육, 멘토링, 기관 연계, 성장 관리 프로그램",
    tone: "green",
    featured: true,
  },
  {
    name: "고성장 실전형",
    signal: "검증과 실행 근거가 높고 확장 전략이 필요한 상태",
    question: "어떻게 더 넓은 시장으로 확장할 것인가?",
    meaning: "시장검증, 실행준비도, 성장성이 높아 다음 단계에서는 투자, R&D, 글로벌, 스케일업 전략을 구체화해야 하는 유형입니다.",
    action: "스케일업 로드맵, 투자 자료, 파트너십, 확장 시장 전략을 보완합니다.",
    support: "스케일업, 투자연계, R&D, 글로벌 진출 프로그램",
    tone: "rose",
  },
];

export const diagnosisSlides = diagnosisJourney.flatMap((group) =>
  group.steps.map((step) => ({
    image: step.image,
    title: step.title,
    caption: step.role,
    role: `${group.title} · ${step.output}`,
    alt: step.alt,
  })),
);
